0:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/grid_gamma_ood/0/19.pt'
  label: "gamma=0"

.1:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/grid_gamma_ood/.1/19.pt'
  label: "gamma=.1"

.5:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/grid_gamma_ood/.5/19.pt'
  label: "gamma=.5"

1:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/grid_gamma_ood/1/18.pt'
  label: "gamma=1"

2:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/grid_gamma_ood/2/19.pt'
  label: "gamma=2"

5:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/grid_gamma_ood/5/19.pt'
  label: "gamma=5"