baseline_ce:
  config: 'configs/eval_carla_fiery_baseline.yaml'
  path: 'outputs/carla/fiery_baseline/19.pt'
  label: "Baseline CE"

evidential_uce:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/carla/fiery_evidential/19.pt'
  label: "Evidential UCE"

evidential_ufocal:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/carla/fiery_evidential_focal/19.pt'
  label: "Evidential UFocal"

evidential_uce_reg:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/carla/fiery_aug_xl/19.pt'
  label: "Evidential UCE + OOD Reg."

evidential_ufocal_reg:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/carla/fiery_aug_f_xl/19.pt'
  label: "Evidential UFocal + OOD Reg."

postnet_uce:
  config: 'configs/eval_carla_fiery_postnet.yaml'
  path: 'outputs/carla/fiery_postnet/19.pt'
  label: "Postnet UCE"

postnet_ufocal:
  config: 'configs/eval_carla_fiery_postnet.yaml'
  path: 'outputs/carla/fiery_postnet_focal/19.pt'
  label: "Postnet UFocal"

dropout_ce:
  config: 'configs/eval_carla_fiery_dropout.yaml'
  path: 'outputs/carla/fiery_baseline/19.pt'
  label: "Dropout CE"

ensemble_ce:
  config: 'configs/eval_carla_fiery_ensemble.yaml'
  path: 'outputs/carla/fiery_ensemble/19.pt'
  label: "Ensemble CE"