baseline_ce:
  config: 'configs/eval_carla_cvt_baseline.yaml'
  path: 'outputs/carla/cvt_baseline/19.pt'
  label: "Baseline CE"

baseline_focal:
  config: 'configs/eval_carla_cvt_baseline.yaml'
  path: 'outputs/carla/cvt_baseline_focal/19.pt'
  label: "Baseline Focal"

evidential_uce:
  config: 'configs/eval_carla_cvt_evidential.yaml'
  path: 'outputs/carla/cvt_evidential/19.pt'
  label: "Evidential UCE"

evidential_ufocal:
  config: 'configs/eval_carla_cvt_evidential.yaml'
  path: 'outputs/carla/cvt_evidential_focal/19.pt'
  label: "Evidential UFocal"

evidential_uce_reg:
  config: 'configs/eval_carla_cvt_evidential.yaml'
  path: 'outputs/carla/cvt_aug_xl/19.pt'
  label: "Evidential UCE + OOD Reg."

#evidential_ufocal_reg:
#  config: 'configs/eval_carla_cvt_evidential.yaml'
#  path: 'outputs/carla/cvt_aug_f_xl/19.pt'
#  label: "Evidential UFocal + OOD Reg."

postnet_uce:
  config: 'configs/eval_carla_cvt_postnet.yaml'
  path: 'outputs/carla/cvt_postnet/19.pt'
  label: "Postnet UCE"

postnet_ufocal:
  config: 'configs/eval_carla_cvt_postnet.yaml'
  path: 'outputs/carla/cvt_postnet_focal/19.pt'
  label: "Postnet UFocal"

dropout_ce:
  config: 'configs/eval_carla_cvt_dropout.yaml'
  path: 'outputs/carla/cvt_baseline/19.pt'
  label: "Dropout CE"

dropout_focal:
  config: 'configs/eval_carla_cvt_dropout.yaml'
  path: 'outputs/carla/cvt_baseline_focal/19.pt'
  label: "Dropout Focal"