0:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: 'outputs/grid_gamma/0/9.pt'
  label: "0"

.5:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: 'outputs/grid_gamma/.5/9.pt'
  label: ".5"

1:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: 'outputs/grid_gamma/1/9.pt'
  label: "1"

2:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: 'outputs/grid_gamma/2/9.pt'
  label: "2"

5:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: 'outputs/grid_gamma/5/9.pt'
  label: "5"