0_25:
  config: 'configs/eval_carla_lss_baseline.yaml'
  path: 'outputs/grid_binary/0_25/19.pt'
  label: "gamma=0, alpha=.25"

0_50:
  config: 'configs/eval_carla_lss_baseline.yaml'
  path: 'outputs/grid_binary/0_50/19.pt'
  label: "gamma=0, alpha=.50"

0_75:
  config: 'configs/eval_carla_lss_baseline.yaml'
  path: 'outputs/grid_binary/0_75/19.pt'
  label: "gamma=0, alpha=.75"

.5_25:
  config: 'configs/eval_carla_lss_baseline.yaml'
  path: 'outputs/grid_binary/.5_25/19.pt'
  label: "gamma=.5, alpha=.25"

.5_50:
  config: 'configs/eval_carla_lss_baseline.yaml'
  path: 'outputs/grid_binary/.5_50/19.pt'
  label: "gamma=.5, alpha=.50"

.5_75:
  config: 'configs/eval_carla_lss_baseline.yaml'
  path: 'outputs/grid_binary/.5_75/19.pt'
  label: "gamma=.5, alpha=.75"

1_25:
  config: 'configs/eval_carla_lss_baseline.yaml'
  path: 'outputs/grid_binary/1_25/19.pt'
  label: "gamma=1, alpha=.25"

1_50:
  config: 'configs/eval_carla_lss_baseline.yaml'
  path: 'outputs/grid_binary/1_50/19.pt'
  label: "gamma=1, alpha=.50"

1_75:
  config: 'configs/eval_carla_lss_baseline.yaml'
  path: 'outputs/grid_binary/1_75/19.pt'
  label: "gamma=1, alpha=.75"

2_25:
  config: 'configs/eval_carla_lss_baseline.yaml'
  path: 'outputs/grid_binary/2_25/19.pt'
  label: "gamma=2, alpha=.25"

2_50:
  config: 'configs/eval_carla_lss_baseline.yaml'
  path: 'outputs/grid_binary/2_50/19.pt'
  label: "gamma=2, alpha=.50"

2_75:
  config: 'configs/eval_carla_lss_baseline.yaml'
  path: 'outputs/grid_binary/2_75/19.pt'
  label: "gamma=2, alpha=.75"

5_25:
  config: 'configs/eval_carla_lss_baseline.yaml'
  path: 'outputs/grid_binary/5_25/19.pt'
  label: "gamma=5, alpha=.25"

5_50:
  config: 'configs/eval_carla_lss_baseline.yaml'
  path: 'outputs/grid_binary/5_50/19.pt'
  label: "gamma=5, alpha=.50"

5_75:
  config: 'configs/eval_carla_lss_baseline.yaml'
  path: 'outputs/grid_binary/5_75/19.pt'
  label: "gamma=5, alpha=.75"