baseline_ce:
  config: 'configs/eval_nuscenes_cvt_baseline.yaml'
  path: 'outputs/nuscenes/cvt_baseline/19.pt'
  label: "Baseline CE"

baseline_focal:
  config: 'configs/eval_nuscenes_cvt_baseline.yaml'
  path: 'outputs/nuscenes/cvt_baseline_focal/19.pt'
  label: "Baseline Focal"

evidential_uce:
  config: 'configs/eval_nuscenes_cvt_evidential.yaml'
  path: 'outputs/nuscenes/cvt_evidential/19.pt'
  label: "Evidential UCE"

evidential_ufocal:
  config: 'configs/eval_nuscenes_cvt_evidential.yaml'
  path: 'outputs/nuscenes/cvt_evidential_focal/19.pt'
  label: "Evidential UFocal"

postnet_uce:
  config: 'configs/eval_nuscenes_cvt_postnet.yaml'
  path: 'outputs/nuscenes/cvt_postnet/19.pt'
  label: "Postnet UCE"

postnet_ufocal:
  config: 'configs/eval_nuscenes_cvt_postnet.yaml'
  path: 'outputs/nuscenes/cvt_postnet_focal/19.pt'
  label: "Postnet UFocal"

dropout_ce:
  config: 'configs/eval_nuscenes_cvt_dropout.yaml'
  path: 'outputs/nuscenes/cvt_baseline/19.pt'
  label: "Dropout CE"

dropout_focal:
  config: 'configs/eval_nuscenes_cvt_dropout.yaml'
  path: 'outputs/nuscenes/cvt_baseline_focal/19.pt'
  label: "Dropout Focal"