0:
  config: 'configs/eval_nuscenes_fiery_evidential.yaml'
  path: 'outputs/grid_nuscenes_ood/0/19.pt'
  label: "OOD Reg.=0"

.1:
  config: 'configs/eval_nuscenes_fiery_evidential.yaml'
  path: 'outputs/grid_nuscenes_ood/.1/19.pt'
  label: "OOD Reg.=.1"

1:
  config: 'configs/eval_nuscenes_fiery_evidential.yaml'
  path: 'outputs/grid_nuscenes_ood/1/19.pt'
  label: "OOD Reg.=1"