
aug:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: 'outputs/aug_o/1.pt'
  label: "Reg."

noaug:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: 'outputs/carla/lss_evidential_schdl/19.pt'
  label: "No Reg."

augl:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: 'outputs/aug_l/13.pt'
  label: "Reg. W. Larger Dataset"
