ufocal:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: './outputs_bin/grid/road/lss_ufocal/19.pt'
  label: "LSS UFocal"

uce_beta=.01:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: './outputs_bin/grid/road/lss_uce_beta=.01/19.pt'
  label: "LSS UCE Entropy Reg. Beta=.01"

uce_beta=.001:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: './outputs_bin/grid/road/lss_uce_beta=.001/19.pt'
  label: "LSS UCE Entropy Reg. Beta=.001"

uce_beta=.0005:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: './outputs_bin/grid/road/lss_uce_beta=.0005/19.pt'
  label: "LSS UCE Entropy Reg. Beta=.0005"