uce:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: '../outputs/aug/none/19.pt'
  label: "UCE OOD Reg."

ufocal:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: '../outputs/aug/none_focal/19.pt'
  label: "UFocal OOD Reg."

ucevac:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: '../outputs/aug/vac_128/19.pt'
  label: "UCE OOD Reg. + Vacuity"

ufocalvac:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: '../outputs/aug/vac_focal_128/19.pt'
  label: "UFocal OOD Reg. + Vacuity"