4:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/grid_nl/vac_4/49.pt'
  label: "k=4"

8:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/grid_nl/vac_16/49.pt'
  label: "k=8"

16:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/grid_nl/vac_32/49.pt'
  label: "k=16"

32:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/grid_nl/vac_32/49.pt'
  label: "k=32"

64:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/grid_nl/vac_64/49.pt'
  label: "k=64"

128:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/grid_nl/vac_128/49.pt'
  label: "k=128"

256:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/grid_nl/vac_256/49.pt'
  label: "k=256"