
ufocal=0:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: './outputs_bin/carla/vehicle/lss_ufocal_gamma=0/19.pt'
  label: "LSS UFocal Gamma=0"

ufocal=.05:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: './outputs_bin/carla/vehicle/lss_ufocal_gamma=.05/19.pt'
  label: "LSS UFocal Gamma=.05"

ufocal=.1:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: './outputs_bin/carla/vehicle/lss_ufocal_gamma=.1/19.pt'
  label: "LSS UFocal Gamma=.1"

ufocal=.5:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: './outputs_bin/carla/vehicle/lss_ufocal_gamma=.5/19.pt'
  label: "LSS UFocal Gamma=.5"

ufocal=1:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: './outputs_bin/carla/vehicle/lss_ufocal_gamma=1/19.pt'
  label: "LSS UFocal Gamma=1"

ufocal=2:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: './outputs_bin/carla/vehicle/lss_ufocal_gamma=2/19.pt'
  label: "LSS UFocal Gamma=2"

uce_beta=0.:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: './outputs_bin/carla/vehicle/lss_uce_beta=0/19.pt'
  label: "LSS UCE Entropy Reg. Beta=.0, LRx4"

uce_beta=.01:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: './outputs_bin/carla/vehicle/lss_uce_beta=.01/19.pt'
  label: "LSS UCE Entropy Reg. Beta=.01"

uce_beta=.001:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: './outputs_bin/carla/vehicle/lss_uce_beta=.001/19.pt'
  label: "LSS UCE Entropy Reg. Beta=.001"

uce_beta=.0005:
  config: 'configs/eval_carla_lss_evidential.yaml'
  path: './outputs_bin/carla/vehicle/lss_uce_beta=.0005/19.pt'
  label: "LSS UCE Entropy Reg. Beta=.0005"