ufocal:
  config: 'configs/eval_nuscenes_lss_evidential.yaml'
  path: './outputs_bin/nuscenes/vehicle/lss_ufocal/19.pt'
  label: "LSS UFocal"

uce_beta=.001:
  config: 'configs/eval_nuscenes_lss_evidential.yaml'
  path: './outputs_bin/nuscenes/vehicle/lss_uce_beta=.001/19.pt'
  label: "LSS UCE Entropy Reg. Beta=.001"