ufocal=.5:
  config: 'configs/eval_nuscenes_lss_evidential.yaml'
  path: './outputs_bin/nuscenes/vehicle/lss_ufocal_gamma=.5/19.pt'
  label: "LSS UFocal Gamma=.5"

uce_beta=.001:
  config: 'configs/eval_nuscenes_lss_evidential.yaml'
  path: './outputs_bin/nuscenes/vehicle/lss_uce_beta=.001/19.pt'
  label: "LSS UCE Entropy Reg. Beta=.001"