ufocal=.5:
  config: 'configs/eval_nuscenes_lss_evidential.yaml'
  path: './outputs_bin/nuscenes/vehicle/lss_ufocal_gamma=.5/19.pt'
  label: "LSS UFocal Gamma=.5"

ufocal=.05:
  config: 'configs/eval_nuscenes_lss_evidential.yaml'
  path: './outputs_bin/nuscenes/vehicle/lss_ufocal_gamma=.05/19.pt'
  label: "LSS UFocal Gamma=.05"

ufocal=.1:
  config: 'configs/eval_nuscenes_lss_evidential.yaml'
  path: './outputs_bin/nuscenes/vehicle/lss_ufocal_gamma=.1/19.pt'
  label: "LSS UFocal Gamma=.1"

ufocal=1:
  config: 'configs/eval_nuscenes_lss_evidential.yaml'
  path: './outputs_bin/nuscenes/vehicle/lss_ufocal_gamma=1/19.pt'
  label: "LSS UFocal Gamma=1"

ufocal=.25:
  config: 'configs/eval_nuscenes_lss_evidential.yaml'
  path: './outputs_bin/nuscenes/vehicle/lss_ufocal_gamma=.25/19.pt'
  label: "LSS UFocal Gamma=.25"

uce_beta=.001:
  config: 'configs/eval_nuscenes_lss_evidential.yaml'
  path: './outputs_bin/nuscenes/vehicle/lss_uce_beta=.001/19.pt'
  label: "LSS UCE Entropy Reg. Beta=.001"