  type: 'evidential'
backbone: 'simplebev'
dataset: 'nuscenes'
logdir: 'outputs/baseline/simplebev_evidential'
gpus: [7]
batch_size: 8
num_workers: 32
pretrained: 'outputs/nuscenes/simplebev_evidential/19.pt'