type: 'evidential_noreg'
backbone: 'cvt'
dataset: 'carla'
logdir: 'outputs/carla/cvt_evidential_noreg'
batch_size: 32
num_workers: 32
weight_decay: 0.0000001
learning_rate: 0.0005
num_epochs: 40
loss: ce
