type: 'baseline'
backbone: 'bevformer'
dataset: 'nuscenes'
logdir: 'outputs/nuscenes/bevformer_baseline'
gpus: [7]
batch_size: 32
num_workers: 32
weight_decay: 0.0000001
learning_rate: 0.0003
num_epochs: 20
loss: ce